services: 
  postgres:
    image: postgres:15
    container_name: postgres-db-news-app
    ports: 
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_admin -d news_app_db -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  news_app:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: news_app
    ports:
      - "5004:5004"
    depends_on: 
      postgres:
        condition: service_healthy
    env_file:
      - .env
      